### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by naveen-kinnal** [dayihengliu/Fine-Grained-Style-Transfer#1]
Hello. I am running your code and I see that these 4 files

```
w2id, id2w = pickle.load(open('/workspace/Data/yelp/w2id_id2w.pkl','rb'))
Y_train, C_train = pickle.load(open('/workspace/Data/yelp/XC_train.pkl','rb'))
Y_dev, C_dev = pickle.load(open('/workspace/Data/yelp/XC_dev.pkl','rb'))
Y_test, C_test = pickle.load(open('/workspace/Data/yelp/XC_test.pkl','rb'))
```

is missing in the TextCNN.ipynb and is not available in the YELP dataset which you directed. Could you please let me know how can I get it.

**Comment by dayihengliu** [comment]
The Yelp and Amazon of the text sentiment transfer task can be downloaded at http://bit.ly/2LHMUsl or https://worksheets.codalab.org/worksheets/0xe3eb416773ed4883bb737662b31b4948/
The Yelp of the text gender style transfer can be downloaded at http://tts.speech.cs.cmu.edu/style_models/gender_classifier.tar

**Comment by naveen-kinnal** [comment]
Hello @dayihengliu Thanks for your reply. But I see in the link that there are only train, dev, test and ref files. But not the above '/workspace/Data/yelp/w2id_id2w.pkl'. Could you please upload those files as well. Thanks

**Comment by dayihengliu** [comment]
> Hello @dayihengliu Thanks for your reply. But I see in the link that there are only train, dev, test and ref files. But not the above '/workspace/Data/yelp/w2id_id2w.pkl'. Could you please upload those files as well. Thanks

Hi, the file w2id_id2w.pkl contains two dict, where w2id and id2w contain the index of each word. You can build the vocabulary by yourself :)

**Comment by naveen-kinnal** [comment]
Thank you. Also, could you please tell how do the below files look 

```
Y_train, C_train = pickle.load(open('/workspace/Data/yelp/XC_train.pkl','rb'))
Y_dev, C_dev = pickle.load(open('/workspace/Data/yelp/XC_dev.pkl','rb'))
Y_test, C_test = pickle.load(open('/workspace/Data/yelp/XC_test.pkl','rb'))
```
Let's say I have 2 YELP files - 1 for negative and 1 for positive. Could you please tell if I should merge both positive and negative sentences into Y_train and have the corresponding labels in C_Train? 

Or is Y_Train for positive and C_Train for negative?

**Comment by dayihengliu** [comment]
> Thank you. Also, could you please tell how do the below files look
> 
> ```
> Y_train, C_train = pickle.load(open('/workspace/Data/yelp/XC_train.pkl','rb'))
> Y_dev, C_dev = pickle.load(open('/workspace/Data/yelp/XC_dev.pkl','rb'))
> Y_test, C_test = pickle.load(open('/workspace/Data/yelp/XC_test.pkl','rb'))
> ```
> 
> Let's say I have 2 YELP files - 1 for negative and 1 for positive. Could you please tell if I should merge both positive and negative sentences into Y_train and have the corresponding labels in C_Train?
> 
> Or is Y_Train for positive and C_Train for negative?

Here C_train is the label data of the training set, Y_dev is the text data of the dev set.
